# Generated by Django 4.2.2 on 2023-06-13 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='need_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='forum.category', verbose_name='category'),
        ),
    ]
