# Generated by Django 4.2.2 on 2023-06-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_thread_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='forum.subcategory', verbose_name='subcategory'),
        ),
    ]
